apiVersion: v1
kind: Service
metadata:
  name: metadata-enhancer-service
spec:
  selector:
    app: metadata-enhancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
